### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by pxx11111** [alanjet/VideoRecorderTest#1]
闪崩

**Comment by alanjet** [comment]
什么机型？可能有些机型由于硬件原因不兼容

**Comment by alanjet** [comment]
写这个小demo时手头上测试机有限，没能考虑所有机型

**Comment by jcj27757** [comment]
我用的是华为的，运行就闪退

**Comment by a342216937** [comment]
闪退的可能是安卓6.0以上的 需要动态获取权限
MainActivity加上以下几行代码:


        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.RECORD_AUDIO}, 1);
        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1);
        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.CAMERA}, 1);
        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS}, 1);

**Comment by qinyang1018** [comment]
![image](https://cloud.githubusercontent.com/assets/15726024/24575711/5ce2705c-16e0-11e7-9474-2212ac58dafe.png)
华为mate8

**Comment by june5753** [comment]
三星 (SM-C5000 Android 6.0.1 API 23)出问题和华为mate8同样的问题，日志也一样。

**Comment by alanjet** [comment]
朋友们，不好意思之前一直忙，现在才过来处理该Issue。正如楼上所说，闪退的Bug是由于缺少运行时权限的申请和处理才出现的。现在我已经提交了新的代码，解决了这个Bug。欢迎大家继续关注和交流。对大家有帮助的话望能给Star鼓励一下，谢谢。
这次更新的信息如下：
修复：因缺少运行时权限处理导致Crash的Bug。
修复：从视频文件界面返回直接退出的Bug。
新增：对相机预览帧的处理方法。

**Comment by HappyJess** [comment]
刚下的代码运行还是闪退

**Comment by yuekong** [comment]
我试了也是
